type ArrayType = string[];
type MapType = { [key: number]: string };
type AddrType = { [key: string]: { seq: number; child: string[]; displayName: string } };
type LocalType = { [key: string]: { seq: number; parent: string; displayName: string } };
//요일
export const weekMap: ArrayType = ['월', '화', '수', '목', '금', '토', '일'];

//주 타입
export const weekTypeMap: MapType = {
  0: '매주',
  1: '격주',
};

//지역 대분류
export const addrMap: AddrType = {
  SEOUL: {
    seq: 1,
    child: [
      'GANGNAMGU',
      'GANGDONGGU',
      'GANGBUKGU',
      'GANGSEOGU_SEOUL',
      'GWANAKGU',
      'GWANGJINGU',
      'GUROGU',
      'GEUMCHEONGU',
      'NOWONGU',
      'DOBONGGU',
      'DONGDAEMUNGU',
      'DONGJAKGU',
      'MAPOGU',
      'SEODAEMUNGU',
      'SEOCHOGU',
      'SEONGDONGGU',
      'SEONGBUKGU',
      'SONGPAGU',
      'YANGCHEONGU',
      'YEONGDEUNGPOGU',
      'YONGSANGU',
      'EUNPYEONG',
      'JONGROGU',
      'JUNGGU_SEOUL',
      'JUNGNANGGU',
    ],
    displayName: '서울특별시',
  },
  BUSAN: {
    seq: 2,
    child: [
      'GANGSEOGU_BUSAN',
      'GEUMJEONGGU',
      'NAMGU',
      'DONGGU',
      'DONGNAEGU',
      'BUSANJINGU',
      'BUKGU',
      'SASANGGU',
      'SAHAGU',
      'SEOGU',
      'SUYEONGGU',
      'YEONJEGU',
      'YEONGDOGU',
      'JUNGGU_BUSAN',
      'HAEUNDAEGU',
      'KIJANGGUN',
    ],
    displayName: '부산광역시',
  },
  DAEGU: {
    seq: 3,
    child: [
      'NAMGU_DAEGU',
      'DALSEOGU',
      'DONGGU_DAEGU',
      'BUKGU_DAEGU',
      'SEOGU_DAEGU',
      'SUSEONGGU',
      'JUNGGU_DEAGU',
      'DALSEONGGUN',
    ],
    displayName: '대구광역시',
  },
  INCHEON: {
    seq: 4,
    child: [
      'GYEYANGGU',
      'NAMGU_INCHEON',
      'NAMDONGGU',
      'DONGGU_INCHEON',
      'BUPYEONGGU',
      'SEOGU_INCHEON',
      'YEONSUGU',
      'JUNGGU_INCHEON',
      'GANGHWA',
      'ONGJIN',
    ],
    displayName: '인천광역시',
  },
  GWANGJU: {
    seq: 5,
    child: ['GWANGSAN', 'NAMGU_GWANGJU', 'DONGGU_GWANGJU', 'BUKGU_GWANGJU', 'SEOGU_GWANGJU'],
    displayName: '광주광역시',
  },
  DAEJEON: {
    seq: 6,
    child: ['DAEDEOKGU', 'DONGGU_DEAJEON', 'SEOGU_DAEJEON', 'YOOSEONGGU', 'JUNGGU_DAEJEON'],
    displayName: '대전광역시',
  },
  ULSAN: {
    seq: 7,
    child: ['NAMGU_ULSAN', 'DONGGU_ULSAN', 'BUKGU_ULSAN', 'JUNGGU_ULSAN', 'ULJUGUN'],
    displayName: '울산광역시',
  },
  SEJONG: {
    seq: 8,
    child: [],
    displayName: '세종특별자치시',
  },
  GANGWON: {
    seq: 9,
    child: [
      'GANGNEUNG',
      'DONGHAE',
      'SAMCHEOK',
      'SOKCHO',
      'WONJU',
      'CHUNCHEON',
      'TAEBAEK',
      'GOSEONG_GANGWON',
      'YANGGU',
      'YANGYANG',
      'YEONGWOL',
      'INJE',
      'JEONGSEON',
      'CHEORWON',
      'PYEONGCHANG',
      'HONGCHEON',
      'HWACHEON',
      'HOENGSEONG',
    ],
    displayName: '강원도',
  },
  GYEONGGI: {
    seq: 10,
    child: [
      'GOYANG_DEOKYANG',
      'GOYANG_ILSANDONG',
      'GOYANG_ILSANSEOGU',
      'GWACHEON',
      'GWANGMYEONG',
      'GWANGJU_GYEONGGI',
      'GURI',
      'GUNPO',
      'GIMPO',
      'NAMYANGJU',
      'DONGDUCHEON',
      'BUCHEON_SOSA',
      'BUCHEON_OJEONG',
      'BUCHEON_WONMI',
      'SEONGNAM_BUNDANG',
      'SEONGNAM_SUJEONG',
      'SEONGNAM_JUNGWON',
      'SUWON_GWONSEON',
      'SUWON_YEONGTONG',
      'SUWON_JANGAN',
      'SUWON_PALDAL',
      'SIHEUNG',
      'ANSAN_DANWON',
      'ANSAN_SANGNOK',
      'ANSEONG',
      'ANYANG_DONGAN',
      'ANYANG_MANAN',
      'YANGJU',
      'OSAN',
      'YONGIN_GIHEUNG',
      'YONGIN_SUYONG',
      'YONGIN_CHEONGIN',
      'UIWANG',
      'UIJEONGBU',
      'ICHEON',
      'PAJU',
      'PYEONGTAEK',
      'POCHEON',
      'HANAM',
      'HWASEONG',
      'GAPYEONG',
      'YANGPYEONG',
      'YEOJU',
      'YEONCHEON',
    ],
    displayName: '경기도',
  },
  GYEONGNAM: {
    seq: 11,
    child: [
      'GEOJE',
      'GIMHAE',
      'MIRYANG',
      'SICHUAN',
      'YANGSAN',
      'JINJU',
      'CHANGWON_MASANHAPPO',
      'CHANGWON_MASANHOEWON',
      'CHANGWON_SEONGSAN',
      'CHANGWON_UICHANG',
      'CHANGWON_JINHAE',
      'TONGYEONG',
      'GEOCHANG',
      'GOSEONG_GYEONGNAM',
      'NAMHAE',
      'SANCHEONG',
      'UIRYEONG',
      'CHANGNYEONG',
      'HADONG',
      'HAMAN',
      'HAMYANG',
      'HAPCHEON',
    ],
    displayName: '경상남도',
  },
  GYEONGBUK: {
    seq: 12,
    child: [
      'GYEONGSAN',
      'GYEONGJU',
      'GUMI',
      'GIMCHEON',
      'MUNGYEONG',
      'SANGJU',
      'ANDONG',
      'YEONGJU',
      'YEONGCHEON',
      'POHANG_NAMGU',
      'POHANG_BUKGU',
      'GORYEONG',
      'GUNWI',
      'BONGHWA',
      'SEONGJU',
      'YEONGDEOK',
      'YEONGYANG',
      'YECHEON',
      'ULLEUNG',
      'ULJIN',
      'UISEONG',
      'QINGDAO',
      'CHEONGSONG',
      'CHILGOK',
    ],
    displayName: '경상북도',
  },
  JEONNAM: {
    seq: 13,
    child: [
      'GWANGYANG',
      'NAJU',
      'MOKPO',
      'SUNCHEON',
      'YEOSU',
      'GANGJIN',
      'GOHEUNG',
      'GOKSEONG',
      'GURYE',
      'DAMYANG',
      'MUAN',
      'BOSEONG',
      'SINAN',
      'YEONGGWANG',
      'YEONGAM',
      'WANDO',
      'JANGSEONG',
      'JANGHEUNG',
      'JINDO',
      'HAMPYEONG',
      'HAENAM',
      'HWASUN',
    ],
    displayName: '전라남도',
  },
  JEONBUK: {
    seq: 14,
    child: [
      'GUNSAN',
      'GIMJE',
      'NAMWON',
      'IKSAN',
      'JEONJU_DEOKJIN',
      'JEONJU_WANSAN',
      'JEONGEUP',
      'GOCHANG',
      'MUJU',
      'BUAN',
      'SUNCHANG',
      'WANJU',
      'IMSIL',
      'JANGSU',
      'JINAN',
    ],
    displayName: '전라북도',
  },
  JEJU: {
    seq: 15,
    child: ['JEJUCITY', 'SEOGWIPO'],
    displayName: '제주특별자치시',
  },
  CHUNGBUK: {
    seq: 16,
    child: [
      'GYERYONG',
      'GONGJU',
      'NONSAN',
      'DANGJIN',
      'BORYEONG',
      'SEOSAN',
      'ASAN',
      'CHEONAN_DONGNAM',
      'CHEONAN_SEOBUK',
      'GEUMSAN',
      'BUYEO',
      'SEOCHEON',
      'YESAN',
      'CHEONGYANG',
      'TAEAN',
      'HONGSEONG',
    ],
    displayName: '충청북도',
  },
  CHUNGNAM: {
    seq: 17,
    child: [
      'JECHEON',
      'CHEONGJU_SANGDANG',
      'CHEONGJU_HEUNGDEOK',
      'CHUNGJU',
      'GOESAN',
      'DANYANG',
      'BOEUN',
      'YEONGDONG',
      'OKCHEON',
      'EUMSEONG',
      'JEUNGPYEONG',
      'JINCHEON',
      'CHEONGWON',
    ],
    displayName: '충청남도',
  },
};
//지역 소분류
export const localMap: LocalType = {
  GANGNAMGU: { seq: 1, parent: 'SEOUL', displayName: '강남구' },
  GANGDONGGU: { seq: 2, parent: 'SEOUL', displayName: '강동구' },
  GANGBUKGU: { seq: 3, parent: 'SEOUL', displayName: '강북구' },
  GANGSEOGU_SEOUL: { seq: 4, parent: 'SEOUL', displayName: '강서구' },
  GWANAKGU: { seq: 5, parent: 'SEOUL', displayName: '관악구' },
  GWANGJINGU: { seq: 6, parent: 'SEOUL', displayName: '광진구' },
  GUROGU: { seq: 7, parent: 'SEOUL', displayName: '구로구' },
  GEUMCHEONGU: { seq: 8, parent: 'SEOUL', displayName: '금천구' },
  NOWONGU: { seq: 9, parent: 'SEOUL', displayName: '노원구' },
  DOBONGGU: { seq: 10, parent: 'SEOUL', displayName: '도봉구' },
  DONGDAEMUNGU: { seq: 11, parent: 'SEOUL', displayName: '동대문구' },
  DONGJAKGU: { seq: 12, parent: 'SEOUL', displayName: '동작구' },
  MAPOGU: { seq: 13, parent: 'SEOUL', displayName: '마포구' },
  SEODAEMUNGU: { seq: 14, parent: 'SEOUL', displayName: '서대문구' },
  SEOCHOGU: { seq: 15, parent: 'SEOUL', displayName: '서초구' },
  SEONGDONGGU: { seq: 16, parent: 'SEOUL', displayName: '성동구' },
  SEONGBUKGU: { seq: 17, parent: 'SEOUL', displayName: '성북구' },
  SONGPAGU: { seq: 18, parent: 'SEOUL', displayName: '송파구' },
  YANGCHEONGU: { seq: 19, parent: 'SEOUL', displayName: '양천구' },
  YEONGDEUNGPOGU: { seq: 20, parent: 'SEOUL', displayName: '영등포구' },
  YONGSANGU: { seq: 21, parent: 'SEOUL', displayName: '용산구' },
  EUNPYEONG: { seq: 22, parent: 'SEOUL', displayName: '은평구' },
  JONGROGU: { seq: 23, parent: 'SEOUL', displayName: '종로구' },
  JUNGGU_SEOUL: { seq: 24, parent: 'SEOUL', displayName: '중구' },
  JUNGNANGGU: { seq: 25, parent: 'SEOUL', displayName: '중랑구' },
  GANGSEOGU_BUSAN: { seq: 26, parent: 'BUSAN', displayName: '강서구' },
  GEUMJEONGGU: { seq: 27, parent: 'BUSAN', displayName: '금정구' },
  NAMGU: { seq: 28, parent: 'BUSAN', displayName: '남구' },
  DONGGU: { seq: 29, parent: 'BUSAN', displayName: '동구' },
  DONGNAEGU: { seq: 30, parent: 'BUSAN', displayName: '동래구' },
  BUSANJINGU: { seq: 31, parent: 'BUSAN', displayName: '부산진구' },
  BUKGU: { seq: 32, parent: 'BUSAN', displayName: '북구' },
  SASANGGU: { seq: 33, parent: 'BUSAN', displayName: '사상구' },
  SAHAGU: { seq: 34, parent: 'BUSAN', displayName: '사하구' },
  SEOGU: { seq: 35, parent: 'BUSAN', displayName: '서구' },
  SUYEONGGU: { seq: 36, parent: 'BUSAN', displayName: '수영구' },
  YEONJEGU: { seq: 37, parent: 'BUSAN', displayName: '연제구' },
  YEONGDOGU: { seq: 38, parent: 'BUSAN', displayName: '영도구' },
  JUNGGU_BUSAN: { seq: 39, parent: 'BUSAN', displayName: '중구' },
  HAEUNDAEGU: { seq: 40, parent: 'BUSAN', displayName: '해운대구' },
  KIJANGGUN: { seq: 41, parent: 'BUSAN', displayName: '기장군' },
  NAMGU_DAEGU: { seq: 42, parent: 'DAEGU', displayName: '남구' },
  DALSEOGU: { seq: 43, parent: 'DAEGU', displayName: '달서구' },
  DONGGU_DAEGU: { seq: 44, parent: 'DAEGU', displayName: '동구' },
  BUKGU_DAEGU: { seq: 45, parent: 'DAEGU', displayName: '북구' },
  SEOGU_DAEGU: { seq: 46, parent: 'DAEGU', displayName: '서구' },
  SUSEONGGU: { seq: 47, parent: 'DAEGU', displayName: '수성구' },
  JUNGGU_DEAGU: { seq: 48, parent: 'DAEGU', displayName: '중구' },
  DALSEONGGUN: { seq: 49, parent: 'DAEGU', displayName: '달성군' },
  GYEYANGGU: { seq: 50, parent: 'INCHEON', displayName: '계양구' },
  NAMGU_INCHEON: { seq: 51, parent: 'INCHEON', displayName: '남구' },
  NAMDONGGU: { seq: 52, parent: 'INCHEON', displayName: '남동구' },
  DONGGU_INCHEON: { seq: 53, parent: 'INCHEON', displayName: '동구' },
  BUPYEONGGU: { seq: 54, parent: 'INCHEON', displayName: '부평구' },
  SEOGU_INCHEON: { seq: 55, parent: 'INCHEON', displayName: '서구' },
  YEONSUGU: { seq: 56, parent: 'INCHEON', displayName: '연수구' },
  JUNGGU_INCHEON: { seq: 57, parent: 'INCHEON', displayName: '중구' },
  GANGHWA: { seq: 58, parent: 'INCHEON', displayName: '강화군' },
  ONGJIN: { seq: 59, parent: 'INCHEON', displayName: '옹진군' },
  GWANGSAN: { seq: 60, parent: 'GWANGJU', displayName: '광산구' },
  NAMGU_GWANGJU: { seq: 61, parent: 'GWANGJU', displayName: '남구' },
  DONGGU_GWANGJU: { seq: 62, parent: 'GWANGJU', displayName: '동구' },
  BUKGU_GWANGJU: { seq: 63, parent: 'GWANGJU', displayName: '북구' },
  SEOGU_GWANGJU: { seq: 64, parent: 'GWANGJU', displayName: '서구' },
  DAEDEOKGU: { seq: 65, parent: 'DAEJEON', displayName: '대덕구' },
  DONGGU_DEAJEON: { seq: 66, parent: 'DAEJEON', displayName: '동구' },
  SEOGU_DAEJEON: { seq: 67, parent: 'DAEJEON', displayName: '서구' },
  YOOSEONGGU: { seq: 68, parent: 'DAEJEON', displayName: '유성구' },
  JUNGGU_DAEJEON: { seq: 69, parent: 'DAEJEON', displayName: '중구' },
  NAMGU_ULSAN: { seq: 70, parent: 'ULSAN', displayName: '남구' },
  DONGGU_ULSAN: { seq: 71, parent: 'ULSAN', displayName: '동구' },
  BUKGU_ULSAN: { seq: 72, parent: 'ULSAN', displayName: '북구' },
  JUNGGU_ULSAN: { seq: 73, parent: 'ULSAN', displayName: '중구' },
  ULJUGUN: { seq: 74, parent: 'ULSAN', displayName: '울주군' },
  GANGNEUNG: { seq: 75, parent: 'GANGWON', displayName: '강릉시' },
  DONGHAE: { seq: 76, parent: 'GANGWON', displayName: '동해시' },
  SAMCHEOK: { seq: 77, parent: 'GANGWON', displayName: '삼척시' },
  SOKCHO: { seq: 78, parent: 'GANGWON', displayName: '속초시' },
  WONJU: { seq: 79, parent: 'GANGWON', displayName: '원주시' },
  CHUNCHEON: { seq: 80, parent: 'GANGWON', displayName: '춘천시' },
  TAEBAEK: { seq: 81, parent: 'GANGWON', displayName: '태백시' },
  GOSEONG_GANGWON: { seq: 82, parent: 'GANGWON', displayName: '고성군' },
  YANGGU: { seq: 83, parent: 'GANGWON', displayName: '양구군' },
  YANGYANG: { seq: 84, parent: 'GANGWON', displayName: '양양군' },
  YEONGWOL: { seq: 85, parent: 'GANGWON', displayName: '영월군' },
  INJE: { seq: 86, parent: 'GANGWON', displayName: '인제군' },
  JEONGSEON: { seq: 87, parent: 'GANGWON', displayName: '정선군' },
  CHEORWON: { seq: 88, parent: 'GANGWON', displayName: '철원군' },
  PYEONGCHANG: { seq: 89, parent: 'GANGWON', displayName: '평창군' },
  HONGCHEON: { seq: 90, parent: 'GANGWON', displayName: '홍천군' },
  HWACHEON: { seq: 91, parent: 'GANGWON', displayName: '화천군' },
  HOENGSEONG: { seq: 92, parent: 'GANGWON', displayName: '횡성군' },
  GOYANG_DEOKYANG: { seq: 93, parent: 'GYEONGGI', displayName: '고양시 덕양구' },
  GOYANG_ILSANDONG: { seq: 94, parent: 'GYEONGGI', displayName: '고양시 일산동구' },
  GOYANG_ILSANSEOGU: { seq: 95, parent: 'GYEONGGI', displayName: '고양시 일산서구' },
  GWACHEON: { seq: 96, parent: 'GYEONGGI', displayName: '과천시' },
  GWANGMYEONG: { seq: 97, parent: 'GYEONGGI', displayName: '광명시' },
  GWANGJU_GYEONGGI: { seq: 98, parent: 'GYEONGGI', displayName: '광주시' },
  GURI: { seq: 99, parent: 'GYEONGGI', displayName: '구리시' },
  GUNPO: { seq: 100, parent: 'GYEONGGI', displayName: '군포시' },
  GIMPO: { seq: 101, parent: 'GYEONGGI', displayName: '김포시' },
  NAMYANGJU: { seq: 102, parent: 'GYEONGGI', displayName: '남양주시' },
  DONGDUCHEON: { seq: 103, parent: 'GYEONGGI', displayName: '동두천시' },
  BUCHEON_SOSA: { seq: 104, parent: 'GYEONGGI', displayName: '부천시 소사구' },
  BUCHEON_OJEONG: { seq: 105, parent: 'GYEONGGI', displayName: '부천시 오정구' },
  BUCHEON_WONMI: { seq: 106, parent: 'GYEONGGI', displayName: '부천시 원미구' },
  SEONGNAM_BUNDANG: { seq: 107, parent: 'GYEONGGI', displayName: '성남시 분당구' },
  SEONGNAM_SUJEONG: { seq: 108, parent: 'GYEONGGI', displayName: '성남시 수정구' },
  SEONGNAM_JUNGWON: { seq: 109, parent: 'GYEONGGI', displayName: '성남시 중원구' },
  SUWON_GWONSEON: { seq: 110, parent: 'GYEONGGI', displayName: '수원시 권선구' },
  SUWON_YEONGTONG: { seq: 111, parent: 'GYEONGGI', displayName: '수원시 영통구' },
  SUWON_JANGAN: { seq: 112, parent: 'GYEONGGI', displayName: '수원시 장안구' },
  SUWON_PALDAL: { seq: 113, parent: 'GYEONGGI', displayName: '수원시 팔달구' },
  SIHEUNG: { seq: 114, parent: 'GYEONGGI', displayName: '시흥시' },
  ANSAN_DANWON: { seq: 115, parent: 'GYEONGGI', displayName: '안산시 단원구' },
  ANSAN_SANGNOK: { seq: 116, parent: 'GYEONGGI', displayName: '안산시 상록구' },
  ANSEONG: { seq: 117, parent: 'GYEONGGI', displayName: '안성시' },
  ANYANG_DONGAN: { seq: 118, parent: 'GYEONGGI', displayName: '안양시 동안구' },
  ANYANG_MANAN: { seq: 119, parent: 'GYEONGGI', displayName: '안양시 만안구' },
  YANGJU: { seq: 120, parent: 'GYEONGGI', displayName: '양주시' },
  OSAN: { seq: 121, parent: 'GYEONGGI', displayName: '오산시' },
  YONGIN_GIHEUNG: { seq: 122, parent: 'GYEONGGI', displayName: '용인시 기흥구' },
  YONGIN_SUYONG: { seq: 123, parent: 'GYEONGGI', displayName: '용인시 수지구' },
  YONGIN_CHEONGIN: { seq: 124, parent: 'GYEONGGI', displayName: '용인시 처인구' },
  UIWANG: { seq: 125, parent: 'GYEONGGI', displayName: '의왕시' },
  UIJEONGBU: { seq: 126, parent: 'GYEONGGI', displayName: '의정부시' },
  ICHEON: { seq: 127, parent: 'GYEONGGI', displayName: '이천시' },
  PAJU: { seq: 128, parent: 'GYEONGGI', displayName: '파주시' },
  PYEONGTAEK: { seq: 129, parent: 'GYEONGGI', displayName: '평택시' },
  POCHEON: { seq: 130, parent: 'GYEONGGI', displayName: '포천시' },
  HANAM: { seq: 131, parent: 'GYEONGGI', displayName: '하남시' },
  HWASEONG: { seq: 132, parent: 'GYEONGGI', displayName: '화성시' },
  GAPYEONG: { seq: 133, parent: 'GYEONGGI', displayName: '가평군' },
  YANGPYEONG: { seq: 134, parent: 'GYEONGGI', displayName: '양평군' },
  YEOJU: { seq: 135, parent: 'GYEONGGI', displayName: '여주군' },
  YEONCHEON: { seq: 136, parent: 'GYEONGGI', displayName: '연천군' },
  GEOJE: { seq: 137, parent: 'GYEONGNAM', displayName: '거제시' },
  GIMHAE: { seq: 138, parent: 'GYEONGNAM', displayName: '김해시' },
  MIRYANG: { seq: 139, parent: 'GYEONGNAM', displayName: '밀양시' },
  SICHUAN: { seq: 140, parent: 'GYEONGNAM', displayName: '사천시' },
  YANGSAN: { seq: 141, parent: 'GYEONGNAM', displayName: '양산시' },
  JINJU: { seq: 142, parent: 'GYEONGNAM', displayName: '진주시' },
  CHANGWON_MASANHAPPO: { seq: 143, parent: 'GYEONGNAM', displayName: '창원시 마산합포구' },
  CHANGWON_MASANHOEWON: { seq: 144, parent: 'GYEONGNAM', displayName: '창원시 마산회원구' },
  CHANGWON_SEONGSAN: { seq: 145, parent: 'GYEONGNAM', displayName: '창원시 성산구' },
  CHANGWON_UICHANG: { seq: 146, parent: 'GYEONGNAM', displayName: '창원시 의창구' },
  CHANGWON_JINHAE: { seq: 147, parent: 'GYEONGNAM', displayName: '창원시 진해구' },
  TONGYEONG: { seq: 148, parent: 'GYEONGNAM', displayName: '통영시' },
  GEOCHANG: { seq: 149, parent: 'GYEONGNAM', displayName: '거창군' },
  GOSEONG_GYEONGNAM: { seq: 150, parent: 'GYEONGNAM', displayName: '고성군' },
  NAMHAE: { seq: 151, parent: 'GYEONGNAM', displayName: '남해군' },
  SANCHEONG: { seq: 152, parent: 'GYEONGNAM', displayName: '산청군' },
  UIRYEONG: { seq: 153, parent: 'GYEONGNAM', displayName: '의령군' },
  CHANGNYEONG: { seq: 154, parent: 'GYEONGNAM', displayName: '창녕군' },
  HADONG: { seq: 155, parent: 'GYEONGNAM', displayName: '하동군' },
  HAMAN: { seq: 156, parent: 'GYEONGNAM', displayName: '함안군' },
  HAMYANG: { seq: 157, parent: 'GYEONGNAM', displayName: '함양군' },
  HAPCHEON: { seq: 158, parent: 'GYEONGNAM', displayName: '합천군' },
  GYEONGSAN: { seq: 159, parent: 'GYEONGBUK', displayName: '경산시' },
  GYEONGJU: { seq: 160, parent: 'GYEONGBUK', displayName: '경주시' },
  GUMI: { seq: 161, parent: 'GYEONGBUK', displayName: '구미시' },
  GIMCHEON: { seq: 162, parent: 'GYEONGBUK', displayName: '김천시' },
  MUNGYEONG: { seq: 163, parent: 'GYEONGBUK', displayName: '문경시' },
  SANGJU: { seq: 164, parent: 'GYEONGBUK', displayName: '상주시' },
  ANDONG: { seq: 165, parent: 'GYEONGBUK', displayName: '안동시' },
  YEONGJU: { seq: 166, parent: 'GYEONGBUK', displayName: '영주시' },
  YEONGCHEON: { seq: 167, parent: 'GYEONGBUK', displayName: '영천시' },
  POHANG_NAMGU: { seq: 168, parent: 'GYEONGBUK', displayName: '포항시 남구' },
  POHANG_BUKGU: { seq: 169, parent: 'GYEONGBUK', displayName: '포항시 북구' },
  GORYEONG: { seq: 170, parent: 'GYEONGBUK', displayName: '고령군' },
  GUNWI: { seq: 171, parent: 'GYEONGBUK', displayName: '군위군' },
  BONGHWA: { seq: 172, parent: 'GYEONGBUK', displayName: '봉화군' },
  SEONGJU: { seq: 173, parent: 'GYEONGBUK', displayName: '성주군' },
  YEONGDEOK: { seq: 174, parent: 'GYEONGBUK', displayName: '영덕군' },
  YEONGYANG: { seq: 175, parent: 'GYEONGBUK', displayName: '영양군' },
  YECHEON: { seq: 176, parent: 'GYEONGBUK', displayName: '예천군' },
  ULLEUNG: { seq: 177, parent: 'GYEONGBUK', displayName: '울릉군' },
  ULJIN: { seq: 178, parent: 'GYEONGBUK', displayName: '울진군' },
  UISEONG: { seq: 179, parent: 'GYEONGBUK', displayName: '의성군' },
  QINGDAO: { seq: 180, parent: 'GYEONGBUK', displayName: '청도군' },
  CHEONGSONG: { seq: 181, parent: 'GYEONGBUK', displayName: '청송군' },
  CHILGOK: { seq: 182, parent: 'GYEONGBUK', displayName: '칠곡군' },
  GWANGYANG: { seq: 183, parent: 'JEONNAM', displayName: '광양시' },
  NAJU: { seq: 184, parent: 'JEONNAM', displayName: '나주시' },
  MOKPO: { seq: 185, parent: 'JEONNAM', displayName: '목포시' },
  SUNCHEON: { seq: 186, parent: 'JEONNAM', displayName: '순천시' },
  YEOSU: { seq: 187, parent: 'JEONNAM', displayName: '여수시' },
  GANGJIN: { seq: 188, parent: 'JEONNAM', displayName: '강진군' },
  GOHEUNG: { seq: 189, parent: 'JEONNAM', displayName: '고흥군' },
  GOKSEONG: { seq: 190, parent: 'JEONNAM', displayName: '곡성군' },
  GURYE: { seq: 191, parent: 'JEONNAM', displayName: '구례군' },
  DAMYANG: { seq: 192, parent: 'JEONNAM', displayName: '담양군' },
  MUAN: { seq: 193, parent: 'JEONNAM', displayName: '무안군' },
  BOSEONG: { seq: 194, parent: 'JEONNAM', displayName: '보성군' },
  SINAN: { seq: 195, parent: 'JEONNAM', displayName: '신안군' },
  YEONGGWANG: { seq: 196, parent: 'JEONNAM', displayName: '영광군' },
  YEONGAM: { seq: 197, parent: 'JEONNAM', displayName: '영암군' },
  WANDO: { seq: 198, parent: 'JEONNAM', displayName: '완도군' },
  JANGSEONG: { seq: 199, parent: 'JEONNAM', displayName: '장성군' },
  JANGHEUNG: { seq: 200, parent: 'JEONNAM', displayName: '장흥군' },
  JINDO: { seq: 201, parent: 'JEONNAM', displayName: '진도군' },
  HAMPYEONG: { seq: 202, parent: 'JEONNAM', displayName: '함평군' },
  HAENAM: { seq: 203, parent: 'JEONNAM', displayName: '해남군' },
  HWASUN: { seq: 204, parent: 'JEONNAM', displayName: '화순군' },
  GUNSAN: { seq: 205, parent: 'JEONBUK', displayName: '군산시' },
  GIMJE: { seq: 206, parent: 'JEONBUK', displayName: '김제시' },
  NAMWON: { seq: 207, parent: 'JEONBUK', displayName: '남원시' },
  IKSAN: { seq: 208, parent: 'JEONBUK', displayName: '익산시' },
  JEONJU_DEOKJIN: { seq: 209, parent: 'JEONBUK', displayName: '전주시 덕진구' },
  JEONJU_WANSAN: { seq: 210, parent: 'JEONBUK', displayName: '전주시 완산구' },
  JEONGEUP: { seq: 211, parent: 'JEONBUK', displayName: '정읍시' },
  GOCHANG: { seq: 212, parent: 'JEONBUK', displayName: '고창군' },
  MUJU: { seq: 213, parent: 'JEONBUK', displayName: '무주군' },
  BUAN: { seq: 214, parent: 'JEONBUK', displayName: '부안군' },
  SUNCHANG: { seq: 215, parent: 'JEONBUK', displayName: '순창군' },
  WANJU: { seq: 216, parent: 'JEONBUK', displayName: '완주군' },
  IMSIL: { seq: 217, parent: 'JEONBUK', displayName: '임실군' },
  JANGSU: { seq: 218, parent: 'JEONBUK', displayName: '장수군' },
  JINAN: { seq: 219, parent: 'JEONBUK', displayName: '진안군' },
  JEJUCITY: { seq: 220, parent: 'JEJU', displayName: '제주시' },
  SEOGWIPO: { seq: 221, parent: 'JEJU', displayName: '서귀포시' },
  GYERYONG: { seq: 222, parent: 'CHUNGBUK', displayName: '계룡시' },
  GONGJU: { seq: 223, parent: 'CHUNGBUK', displayName: '공주시' },
  NONSAN: { seq: 224, parent: 'CHUNGBUK', displayName: '논산시' },
  DANGJIN: { seq: 225, parent: 'CHUNGBUK', displayName: '당진시' },
  BORYEONG: { seq: 226, parent: 'CHUNGBUK', displayName: '보령시' },
  SEOSAN: { seq: 227, parent: 'CHUNGBUK', displayName: '서산시' },
  ASAN: { seq: 228, parent: 'CHUNGBUK', displayName: '아산시' },
  CHEONAN_DONGNAM: { seq: 229, parent: 'CHUNGBUK', displayName: '천안시 동남구' },
  CHEONAN_SEOBUK: { seq: 230, parent: 'CHUNGBUK', displayName: '천안시 서북구' },
  GEUMSAN: { seq: 231, parent: 'CHUNGBUK', displayName: '금산군' },
  BUYEO: { seq: 232, parent: 'CHUNGBUK', displayName: '부여군' },
  SEOCHEON: { seq: 233, parent: 'CHUNGBUK', displayName: '서천군' },
  YESAN: { seq: 234, parent: 'CHUNGBUK', displayName: '예산군' },
  CHEONGYANG: { seq: 235, parent: 'CHUNGBUK', displayName: '청양군' },
  TAEAN: { seq: 236, parent: 'CHUNGBUK', displayName: '태안군' },
  HONGSEONG: { seq: 237, parent: 'CHUNGBUK', displayName: '홍성군' },
  JECHEON: { seq: 238, parent: 'CHUNGNAM', displayName: '제천시' },
  CHEONGJU_SANGDANG: { seq: 239, parent: 'CHUNGNAM', displayName: '청주시 상당구' },
  CHEONGJU_HEUNGDEOK: { seq: 240, parent: 'CHUNGNAM', displayName: '청주시 홍덕구' },
  CHUNGJU: { seq: 241, parent: 'CHUNGNAM', displayName: '충주시' },
  GOESAN: { seq: 242, parent: 'CHUNGNAM', displayName: '괴산군' },
  DANYANG: { seq: 243, parent: 'CHUNGNAM', displayName: '단양군' },
  BOEUN: { seq: 244, parent: 'CHUNGNAM', displayName: '보은군' },
  YEONGDONG: { seq: 245, parent: 'CHUNGNAM', displayName: '영동군' },
  OKCHEON: { seq: 246, parent: 'CHUNGNAM', displayName: '옥천군' },
  EUMSEONG: { seq: 247, parent: 'CHUNGNAM', displayName: '음성군' },
  JEUNGPYEONG: { seq: 248, parent: 'CHUNGNAM', displayName: '증평군' },
  JINCHEON: { seq: 249, parent: 'CHUNGNAM', displayName: '진천군' },
  CHEONGWON: { seq: 250, parent: 'CHUNGNAM', displayName: '청원군' },
};
